@startuml
left to right direction
skinparam packageStyle rectangle

actor User
actor Admin

rectangle "Reservation System" {

  User --> (Get All User's Reservations)
  User --> (Get User's Reservation By ID)
  User --> (Create User's Reservation)
  User --> (Update User's Reservation)
  User --> (Delete User's Reservation)

  (Get All Reservations) <-- Admin
  (Get Reservation By ID) <-- Admin
  (Create A New Reservation) <-- Admin
  (Update Reservation By ID) <-- Admin
  (Delete Reservation By ID) <-- Admin

}

@enduml