@startuml Manage Reservation (DELETE)

header Sameple VacQ Sequence Diagram
footer Page %page% of %lastpage%
title "Delete One Reservations (DELETE)"

skinparam dpi 180
skinparam ParticipantPadding 30
skinparam MessagePadding 25
skinparam maxMessageSize 40

participant "Client" as client
participant "<<javaScript>>\n:server" as server
participant "<<middleware>>\n:auth/protect" as middleware
participant "<<router>>\n:reservations" as routerReservations
participant "<<controllers>>\n:reservations" as controllersReservations
participant "<<model>>\n:Reservation" as modelReservation
database "<<MongoDB>>\n:reservations" as ReservationsDatabase

client -> server ++: req.delete('/api/v1/reservations/:id')
server -> middleware ++: verify token\nset req.user
middleware --> server --: next()

server -> routerReservations ++: app.use('/api/v1/reservations',reservations)


routerReservations -> controllersReservations ++: deleteReservation()

controllersReservations -> modelReservation ++: deleteOne(id: user.params.id)

note right of controllersReservations
response depends on:
- req.user.role (admin / not admin) or ownership of the data
end note

modelReservation -> ReservationsDatabase ++: ReservationSchema
ReservationsDatabase --> modelReservation --: reservation
modelReservation --> controllersReservations --: reservation

controllersReservations --> client --: response

@enduml